defaults:
  - dataset: libero
  - _self_

# Model selection: 'dreamer' or 'simple'
model_type: 'simple'
use_random_data: true # If true, the trainer will collect random trajectories and add them to the buffer, instead of training a world model and using it for planning.
use_policy: true # If true, the trainer will train a policy network instead of a world model. The policy will be trained using behavior cloning on the collected trajectories.

# Loss coefficients for model training
loss_coeffs:
  pred_coeff: 1.
  dyn_coeff: 1.
  rep_coeff: 0.1

# CEM Planner parameters
planner:
  type: cem  # Default planner type
  horizon: 12
  num_iterations: 100
  num_samples: 100
  num_elites: 10
  temperature: 0.3
  learning_rate: 0.001

experiment:
  name: hw2
  project: Homework 2 - Dreamer and CEM Planner
  description: "simple env with 64pix images and pose data"

# Training parameters
training:
  num_epochs: 100  # Default number of training epochs

# Experiment name (can be overridden)
exp_name: "default_exp"

# Model type: "transformer" or "convnet" or "dataset" or "dense"
model: 
  type: "transformer"

batch_size: 64 # how many independent sequences will we process in parallel?
max_block_size: 16 ## Tokens for langauge processing
vocab_size: 32 ## Will be overidden by code
n_patches: 8
patch_size: 8
max_iters: 5000
eval_interval: 100 # How often to run eval over the validation set
learning_rate: 3e-4
lr_schedule: linear ## ['inverse_sqrt', 'linear']
eval_iters: 5
policy:
  action_stacking: 1
  obs_stacking: 1
  use_image_augmentations: false
  dtype: 'float32'
  use_pose_data: 1
  random_masking_enabled: false  # Set to false to skip random masking, true to enable it
  use_last_action: false  # New flag to indicate whether to use last action as input
  add_noise_to_state: true  # New flag to indicate whether to add noise to state
  state_noise_std: 0.01  # Standard deviation of the noise to be added
  sequence_length: 8
  dropout: 0.2

testing: false
eval_vid_iters: 50
gradient_accumulation_steps: 1

simEval: ["libero"]
sim:
  eval_episodes: 1
  eval_tasks: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # List of task indices to evaluate on; length should match eval_episodes
  episode_length: 300
  task_set: "libero_spatial"
  libero_init_state_file: "/openvla/experiments/robot/libero/libero_spatial_init_states_and_goals.hdf"
  libero_init_state_hf_repo: "gberseth/libero_spatial_init_states"

# ------------

r_seed: 1337
device: "cuda"
n_embd: 512
n_head: 16
n_blocks: 4
action_dim: 7
load_action_bounds: true


## Model hyperparameters
image_shape: [64, 64, 3]
data_shuffel_interval: 1000 ## How often to reshuffle the data buffer, grabbing new random sequences from the cloud.

profiler:
  enable: false
  params:
    # record_shapes: true
    profile_memory: true
    with_stack: true
    use_cuda: true